server:
  port: 8080

spring:
  config:
    import: system-prompt.yml, secrets.yml
  ai:
  #  vertex:
  #    ai:
  #      gemini:
  #        project-id: <YOUR-GOOGLE-CLOUD-PROJECT-ID>
  #        location: "europe-west1"
  #        model: "gemini-2.0-flash-lite"


  #  retry:
  #    backoff:
  #      initial-interval: 22s
  #      multiplier: 2
    openai:
      chat:
        options:
          model: "gpt-4.1-nano"
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral

  datasource:
    # Use an in-memory H2 database named 'testdb'
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  # H2 Database specific settings
  h2.console:
    # Enable the H2 web console for viewing the database structure/data
    enabled: true
    # Access the console at http://localhost:8080/h2-console
    path: /h2-console

  # JPA (Hibernate) configuration
  jpa:
    # We are using manual schema scripts (schema.sql), so disable Hibernate's automatic DDL generation
    hibernate:
      ddl-auto: none
    # Set the dialect specifically for H2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false

  # Database Initialization (runs the SQL scripts)
  sql:
    init:
      # Enable initialization scripts
      mode: always
      # Specifies the SQL file that defines the database structure (schema)
      schema-locations: classpath:sql/schema.sql
      # Specifies the SQL file that populates the database with initial data
      #data-locations: classpath:sql/data.sql
app:
  data:
    unzip-dir: data
    gdp-url: https://api.worldbank.org/v2/en/indicator/NY.GDP.MKTP.CD?downloadformat=csv
    population-url: https://api.worldbank.org/v2/en/indicator/SP.POP.TOTL?downloadformat=csv